### ISSUE TITLE
Not able to move with the mouse on Windows

### ISSUE THREAD

**Issue by michidk** [Game4all/vx_bevy#19]
I am not able to move around using the mouse on Windows 10. The camera keeps facing downwards.
It can be fixed by uncommenting this line: https://github.com/Game4all/vx_bevy/blob/master/src/voxel/world/player.rs#L23

**Comment by Game4all** [comment]
Sounds like cursor isn't in locked mode. Try pressing escape to toogle cursor locking and enable moving the camera around.
