### ISSUE TITLE
Simdnoise doesn't support non-x86

### ISSUE THREAD

**Issue by merlinfuchs** [Game4all/vx_bevy#3]
For anyone trying to get the world generation to work on a non-x86-target, you need to patch the `3.1.6` version of `simdnoise` with this commit https://github.com/jackmott/rust-simd-noise/commit/23c690578a2ce2bc5f9d6eb7faf730ea909baa47 .

I made a fork of `simdnoise` which does the trick for me:
```toml
simdnoise = { git = "https://github.com/merlinfuchs/rust-simd-noise", branch = "3.1.6-patch" }
```

Feel free to close this, just leaving this here if anyone runs into the same problem.

**Comment by merlinfuchs** [comment]
Btw. the master of https://github.com/jackmott/rust-simd-noise doesn't work because the noise functions seems to produce different results.

**Comment by Game4all** [comment]
I thought simd stuff in the crate was platform-gated and that it would simply fallback to scalar on non-x86, that's unfortunate. I think opening a PR upstream for fixing this would be nice. In the mean-time maintaining a fork sounds good.

**Comment by merlinfuchs** [comment]
I haven't looked into what has changed exactly on master, but the results are very different. You will see what I mean when you run vx_bevy with the master branch of simdnoise.

**Comment by Game4all** [comment]
Checked out rust-simd-noise master branch, problem is due to the value scale of noise that changed, scaling it back to [-1.0, 1.0] should fix things.

**Comment by Game4all** [comment]
#22
